{
 "title": "Proofs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Proofs in epoch",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ol_proofs_in_epoch", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Tower height",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "ol_tower_height", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Latest epoch mining",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "ol_latest_epoch_mining", "legendFormat": "{{id}}" }
   ]
  }
 ]
}